export const COLORS = {
  WHITE: "#FFFFFF",
  ORANGE: "#FB8E31",
  ORANGE_LIGHT: "#FFC38F",
  YELLOW: "#F9D60C",
  YELLOW_LIGHT: "#FCEA85",
  BLUE: "#2A59FF",
  BLUE_LIGHT: "#5F82FF",
  PINK: "#FF3162",
  PINK_LIGHT: "#FF88A4",
};
